# Generated by Django 6.0.3 on 2026-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Video duration in seconds'),
        ),
    ]
