# Generated by Django 5.2.4 on 2026-03-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_module_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category_id',
            field=models.IntegerField(default=1, help_text='Moodle Category ID'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='course',
            name='short_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='moodle_page_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='moodle_quiz_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='passing_score',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='module',
            name='quiz_data',
            field=models.JSONField(blank=True, help_text='Store questions, options, and answers', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='theory_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='auto_sync_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
