# Generated by Django 5.2.4 on 2026-03-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0003_course_category_id_course_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_auto_issue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='allowed_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='module',
            name='browser_lock_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='disable_fast_forward',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='minimum_watch_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='must_complete_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='quiz_time_limit_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='release_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='release_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='required_replays',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='module',
            name='webcam_snapshot_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='checkpoints_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='quiz_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='replay_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='theory_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchevent',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CourseCertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(default='Default Certificate', max_length=120)),
                ('signer_name', models.CharField(blank=True, max_length=120)),
                ('signer_title', models.CharField(blank=True, max_length=120)),
                ('qr_verify_base_url', models.URLField(blank=True)),
                ('auto_issue', models.BooleanField(default=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_host', models.CharField(blank=True, max_length=255)),
                ('signed_url_secret', models.CharField(blank=True, max_length=255)),
                ('certificate_signer', models.CharField(blank=True, max_length=255)),
                ('token_ttl_seconds', models.PositiveIntegerField(default=300)),
                ('attention_monitoring_enabled', models.BooleanField(default=False)),
                ('siem_endpoint', models.URLField(blank=True)),
                ('blockchain_anchor_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=64, unique=True)),
                ('verification_hash', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_certificates', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('score', models.FloatField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'module', 'attempt_number')},
            },
        ),
    ]
