# Generated by Django 5.2.4 on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_enforcement_and_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='hls_playlist',
            field=models.FileField(blank=True, null=True, upload_to='videos/hls/'),
        ),
        migrations.AddField(
            model_name='module',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/raw/'),
        ),
    ]
