# Generated by Django 5.2.4 on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_module_local_video_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='moodle_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='moodle_sync_status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')],
                default='pending',
                max_length=20,
            ),
        ),
    ]
