# Generated by Django 5.2.4 on 2026-03-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_studentprofile_approval_status_and_platformsetting_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='theory/images/'),
        ),
        migrations.AddField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('video', 'Video'), ('theory', 'Theory'), ('quiz', 'Quiz')], default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='theory/pdfs/'),
        ),
    ]
