# Generated by Django 5.2.4 on 2026-03-25 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_quizquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.RemoveField(
            model_name='module',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='module',
            name='hls_playlist',
        ),
        migrations.RemoveField(
            model_name='module',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='module',
            name='minimum_watch_percentage',
        ),
        migrations.RemoveField(
            model_name='module',
            name='moodle_page_id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='moodle_quiz_id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='module',
            name='quiz_data',
        ),
        migrations.RemoveField(
            model_name='module',
            name='theory_content',
        ),
        migrations.RemoveField(
            model_name='module',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='module',
            name='video_url',
        ),
        migrations.AddField(
            model_name='module',
            name='min_watch',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='module',
            name='mandatory_checkpoints',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('video', 'Video'), ('theory', 'Theory'), ('quiz', 'Quiz')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuizModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_details', to='student.module')),
            ],
        ),
        migrations.CreateModel(
            name='QuizModuleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='student.quizmodule')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theory_details', to='student.module')),
            ],
        ),
        migrations.CreateModel(
            name='VideoModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_details', to='student.module')),
            ],
        ),
    ]
