# Generated by Django 5.2.4 on 2026-03-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_remove_module_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='allowed_attempts',
        ),
        migrations.RemoveField(
            model_name='module',
            name='browser_lock_required',
        ),
        migrations.RemoveField(
            model_name='module',
            name='disable_fast_forward',
        ),
        migrations.RemoveField(
            model_name='module',
            name='disable_seeking',
        ),
        migrations.RemoveField(
            model_name='module',
            name='mandatory_checkpoints',
        ),
        migrations.RemoveField(
            model_name='module',
            name='min_watch',
        ),
        migrations.RemoveField(
            model_name='module',
            name='minimum_watch_seconds',
        ),
        migrations.RemoveField(
            model_name='module',
            name='must_complete_quiz',
        ),
        migrations.RemoveField(
            model_name='module',
            name='passing_score',
        ),
        migrations.RemoveField(
            model_name='module',
            name='quiz_time_limit_seconds',
        ),
        migrations.RemoveField(
            model_name='module',
            name='release_end_at',
        ),
        migrations.RemoveField(
            model_name='module',
            name='release_start_at',
        ),
        migrations.RemoveField(
            model_name='module',
            name='required_replays',
        ),
        migrations.RemoveField(
            model_name='module',
            name='webcam_snapshot_enabled',
        ),
        migrations.AddField(
            model_name='quizmodule',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='quizmodule',
            name='passing_score',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='videomodule',
            name='allow_seek',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videomodule',
            name='min_watch_percentage',
            field=models.IntegerField(default=80),
        ),
    ]
