# Generated by Django 5.2.4 on 2026-03-25 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_remove_module_allowed_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='videomodule',
            old_name='min_watch_percentage',
            new_name='min_watch_percent',
        ),
        migrations.AddField(
            model_name='videomodule',
            name='checkpoint_interval',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='videomodule',
            name='disable_fast_forward',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videomodule',
            name='enable_checkpoints',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videomodule',
            name='min_watch_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videomodule',
            name='required_replays',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='VideoEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('timestamp', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.FloatField(default=0)),
                ('watch_percent', models.FloatField(default=0)),
                ('replay_count', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
