# Generated by Django 5.2.4 on 2026-03-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_rename_min_watch_percentage_videomodule_min_watch_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodule',
            name='dash_manifest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videomodule',
            name='processing_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
