# Generated by Django 5.2.4 on 2026-03-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_add_course_thumbnail_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='moodle_id',
            field=models.IntegerField(blank=True, help_text='Moodle activity/module ID', null=True),
        ),
    ]
