# Generated by Django 5.2.4 on 2026-03-27 06:41

from django.db import migrations, models
import os


def migrate_module_data(apps, schema_editor):
    Module = apps.get_model('student', 'Module')
    VideoModule = apps.get_model('student', 'VideoModule')
    TheoryModule = apps.get_model('student', 'TheoryModule')
    QuizModule = apps.get_model('student', 'QuizModule')
    QuizModuleQuestion = apps.get_model('student', 'QuizModuleQuestion')

    # Migrate video modules
    for video_module in VideoModule.objects.all():
        module = video_module.module
        module.type = 'video'
        module.video_file = video_module.video_file
        if hasattr(video_module, 'dash_manifest') and video_module.dash_manifest:
            module.dash_manifest = video_module.dash_manifest
        module.save()

    # Migrate theory modules
    for theory_module in TheoryModule.objects.all():
        module = theory_module.module
        module.type = 'theory'
        module.content = theory_module.content
        # Combine pdf and image into single file field if needed
        if theory_module.pdf:
            module.file = theory_module.pdf
        elif theory_module.image:
            module.file = theory_module.image
        module.save()

    # Migrate quiz modules
    for quiz_module in QuizModule.objects.all():
        module = quiz_module.module
        module.type = 'quiz'
        # Get the first question for this quiz
        questions = QuizModuleQuestion.objects.filter(quiz=quiz_module)
        if questions.exists():
            first_question = questions.first()
            module.question = first_question.question_text
            module.option_a = first_question.option_a
            module.option_b = first_question.option_b
            module.option_c = first_question.option_c
            module.option_d = first_question.option_d
            module.correct_answer = first_question.correct_answer
        module.save()


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_module_moodle_id'),
    ]

    operations = [
        # Rename module_type to type
        migrations.RenameField(
            model_name='module',
            old_name='module_type',
            new_name='type',
        ),
        # Add new unified fields
        migrations.AddField(
            model_name='module',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='module',
            name='dash_manifest',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='module',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='theory/'),
        ),
        migrations.AddField(
            model_name='module',
            name='option_a',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='module',
            name='option_b',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='module',
            name='option_c',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='module',
            name='option_d',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='module',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/raw/'),
        ),
        # Migrate data from separate tables
        migrations.RunPython(migrate_module_data, migrations.RunPython.noop),
        # Delete old model tables
        migrations.DeleteModel(
            name='QuizModule',
        ),
        migrations.DeleteModel(
            name='QuizModuleQuestion',
        ),
        migrations.DeleteModel(
            name='TheoryModule',
        ),
        migrations.DeleteModel(
            name='VideoModule',
        ),
    ]
