# Generated by Django 6.0.3 on 2026-03-30 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_unify_module_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='module',
            name='moodle_id',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('pending_teacher', 'Pending Teacher Approval'), ('pending_admin', 'Pending Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_teacher', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
