# Generated by Django 5.2.4 on 2026-03-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_certificate_options_remove_module_moodle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_signer_name',
            field=models.CharField(default='Coordinator / Authority', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_signer_title',
            field=models.CharField(default='Head of Department', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
