# Generated by Django 5.2.4 on 2026-03-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_module_assignment_task_file_alter_module_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
