# Generated by Django 5.2.4 on 2026-04-01 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_alter_course_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='module',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='module',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='module',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='module',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='module',
            name='option_d',
        ),
        migrations.RemoveField(
            model_name='module',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_legacy', to='student.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
