# Generated by Django 5.2.4 on 2026-04-01 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_alter_question_options_remove_module_correct_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='student.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'question')},
            },
        ),
    ]
