# Generated by Django 5.2.4 on 2026-04-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_questionattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='video_url',
            field=models.URLField(blank=True, help_text='[DEPRECATED] Use local video_file instead.', max_length=500, null=True),
        ),
    ]
