# Generated by Django 5.2.4 on 2026-04-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_enrollment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='certificate_signer_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='certificate_signer_title',
        ),
        migrations.RemoveField(
            model_name='platformsetting',
            name='certificate_signer',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/teacher/'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='admin_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/admin/'),
        ),
    ]
