# Generated by Django 5.2.4 on 2026-04-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_remove_course_certificate_signer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
